# Generated by Django 5.0.7 on 2025-08-23 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('tipo', models.CharField(choices=[('standard', 'Standard'), ('luxo', 'Luxo'), ('suite', 'Suite')], max_length=20)),
                ('capacidade', models.PositiveIntegerField(default=2)),
                ('ativo', models.BooleanField(default=True)),
                ('tarifa', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FotoQuarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='quartos/')),
                ('descricao', models.CharField(blank=True, max_length=100)),
                ('quarto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='quartos.quarto')),
            ],
        ),
        migrations.AddField(
            model_name='quarto',
            name='servicos',
            field=models.ManyToManyField(blank=True, to='quartos.servico'),
        ),
    ]
