# Generated by Django 5.0.7 on 2025-08-31 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quartos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarto',
            name='ocupado',
            field=models.BooleanField(default=False),
        ),
    ]
