# Generated by Django 5.0.7 on 2025-08-31 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quartos', '0002_quarto_ocupado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarto',
            name='tipo',
            field=models.CharField(choices=[('Standard', 'Standard'), ('Luxo', 'Luxo'), ('Luite', 'Suite')], max_length=20),
        ),
    ]
