# Generated by Django 5.0.7 on 2025-08-23 17:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('tipo_quarto', models.CharField(choices=[('standard', 'Standard'), ('luxo', 'Luxo'), ('suite', 'Suite')], max_length=50)),
                ('data_entrada', models.DateField()),
                ('data_saida', models.DateField()),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendente', max_length=20)),
            ],
        ),
    ]
