# Generated by Django 5.0.7 on 2025-08-23 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quartos', '0001_initial'),
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='quarto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='quartos.quarto'),
            preserve_default=False,
        ),
    ]
