# Generated by Django 5.0.7 on 2025-08-23 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quartos', '0001_initial'),
        ('reservas', '0002_reserva_quarto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='quarto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='quartos.quarto'),
        ),
    ]
