# Generated by Django 5.0.7 on 2025-08-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_alter_reserva_quarto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='data_entrada',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data_saida',
            field=models.DateTimeField(),
        ),
    ]
